### ISSUE TITLE
Do not use $string{$index}

### ISSUE THREAD

**Issue by thiemowmde** [JeroenDeDauw/JsonDumpReader#2]
The `$line{0}` syntax to access characters in a string is deprecated. Personally I avoid both and prefer substr.

**Comment by JeroenDeDauw** [comment]
Is doing `substr` not bad for performance in such a usecase?

**Comment by thiemowmde** [comment]
I have never micro-benchmarked this. I expect it to be similar.

**Comment by JeroenDeDauw** [comment]
Seems that since PHP 5.5 you can do `$str[0]`: http://php.net/manual/en/migration55.new-features.php

**Comment by thiemowmde** [comment]
PHP 5.5 added support for string literals, e.g. `"string"[0]`. For variables this is possible since at least PHP 4. The `{0}` syntax was supposed to be deprecated in PHP 6.

**Comment by JeroenDeDauw** [comment]
PR welcome, I will not do this myself
